### PR TITLE
BugFix: Add support for `withControlled` from vee-validate@4.7.0

### PR DESCRIPTION
**Pull request by pleek91**
# Description
Vee validate introduced a method property on `handleSubmit` which we are wrapping in our `useForm` composition. This caused a type error because we didn't implement the same type. 

Added support for `withControlled` which fixes the type error.

### CODE REVIEW

**Comment by zhen0** [comment]
Do we still need this one @pleek91?

**Comment by pleek91** [comment]
> Do we still need this one @pleek91? 

We do if we want to update. There's no reason to not merge this. It just never got a review and was forgotten

**Comment by zhen0** [comment]
hmmm that wasn't what I expected to happen

**Comment by zhen0** [comment]
Closing in favor of #1068

**Pull request closed without merging**
